
#include "ClientApp.hpp"

#include <SDL3/SDL_keycode.h>
#include <imgui.h>

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include <glm/glm.hpp>

#include "absl/flags/flag.h"
#include "absl/flags/parse.h"
#include "frame/api.h"
#include "frame/file/file_system.h"
#include "frame/gui/draw_gui_factory.h"
#include "frame/gui/gui_window_interface.h"
#include "frame/json/parse_level.h"
#include "frame/window_factory.h"
#include "frame/window_interface.h"

ABSL_FLAG(std::string, server_address, "localhost:50051", "gRPC server address.");
ABSL_FLAG(std::string, player_name, "",
          "Player name to join as. If empty, the client prompts interactively.");

namespace grpcmud::client
{
namespace
{
constexpr std::size_t kMaxLogLines = 128;
constexpr glm::uvec2 kDefaultWindowSize{1280u, 720u};
constexpr float kCellSize = 2.0f;
constexpr float kHalfCell = kCellSize * 0.5f;
constexpr float kFloorThickness = 0.10f;
constexpr float kFloorCenterY = -0.62f;
constexpr float kGroundY = kFloorCenterY + (kFloorThickness * 0.5f);
constexpr float kBaseFloorThickness = 0.08f;
constexpr float kBaseFloorCenterY = -0.72f;
constexpr float kBaseFloorMarginCells = 2.0f;
constexpr float kWallThickness = 0.18f;
constexpr float kWallHeight = 2.3f;
constexpr float kWallCenterY = kGroundY + (kWallHeight * 0.5f) - 0.04f;
constexpr float kWallCubeSize = kCellSize + 0.02f;
constexpr float kPlayerHeight = 1.75f;
constexpr float kPlayerWidth = 0.55f;
constexpr float kNpcHeight = 1.55f;
constexpr float kNpcWidth = 0.65f;
constexpr float kCameraHeight = 0.92f;
constexpr float kCameraForwardDistance = 2.0f;
constexpr float kCameraNearClip = 0.12f;

std::int64_t CoordKey(int x, int y)
{
    return (static_cast<std::int64_t>(x) << 32) ^ static_cast<std::uint32_t>(y);
}

struct FacingVec
{
    float x = 0.0f;
    float z = -1.0f;
};

FacingVec ToFacingVec(mud::v1::Direction direction)
{
    switch (direction)
    {
    case mud::v1::DIRECTION_NORTH:
        return {0.0f, -1.0f};
    case mud::v1::DIRECTION_EAST:
        return {1.0f, 0.0f};
    case mud::v1::DIRECTION_SOUTH:
        return {0.0f, 1.0f};
    case mud::v1::DIRECTION_WEST:
        return {-1.0f, 0.0f};
    case mud::v1::DIRECTION_UNSPECIFIED:
    default:
        return {0.0f, -1.0f};
    }
}

struct CubeSpec
{
    float tx = 0.0f;
    float ty = 0.0f;
    float tz = 0.0f;
    float sx = 1.0f;
    float sy = 1.0f;
    float sz = 1.0f;
};

void AddCubeSpec(std::vector<CubeSpec>& cubes, float tx, float ty, float tz, float sx, float sy,
                 float sz)
{
    cubes.push_back(CubeSpec{tx, ty, tz, sx, sy, sz});
}

void WriteRaytraceObj(const std::filesystem::path& path, const std::vector<CubeSpec>& cubes)
{
    std::vector<CubeSpec> final_cubes = cubes;
    if (final_cubes.empty())
    {
        final_cubes.push_back(CubeSpec{100000.0f, -100000.0f, 100000.0f, 0.01f, 0.01f, 0.01f});
    }

    std::ofstream out(path, std::ios::trunc);
    if (!out.is_open())
    {
        throw std::runtime_error("Failed to write OBJ file: " + path.string());
    }

    out << "# generated by grpcMUD client\n";
    out << "o mesh\n";
    out << std::fixed << std::setprecision(5);

    int next_index = 1;
    const auto emit_quad = [&](const glm::vec3& a, const glm::vec3& b, const glm::vec3& c,
                               const glm::vec3& d, const glm::vec3& normal)
    {
        const int base = next_index;
        const std::array<glm::vec3, 4> points{a, b, c, d};
        const std::array<glm::vec2, 4> uv{{{0.0f, 0.0f},
                                           {1.0f, 0.0f},
                                           {1.0f, 1.0f},
                                           {0.0f, 1.0f}}};
        for (std::size_t i = 0; i < points.size(); ++i)
        {
            out << "v " << points[i].x << ' ' << points[i].y << ' ' << points[i].z << '\n';
            out << "vt " << uv[i].x << ' ' << uv[i].y << '\n';
            out << "vn " << normal.x << ' ' << normal.y << ' ' << normal.z << '\n';
        }
        out << "f " << base << '/' << base << '/' << base << ' ' << (base + 1) << '/'
            << (base + 1) << '/' << (base + 1) << ' ' << (base + 2) << '/' << (base + 2) << '/'
            << (base + 2) << '\n';
        out << "f " << base << '/' << base << '/' << base << ' ' << (base + 2) << '/'
            << (base + 2) << '/' << (base + 2) << ' ' << (base + 3) << '/' << (base + 3) << '/'
            << (base + 3) << '\n';
        next_index += 4;
    };

    for (const CubeSpec& cube : final_cubes)
    {
        const float min_x = cube.tx - (cube.sx * 0.5f);
        const float max_x = cube.tx + (cube.sx * 0.5f);
        const float min_y = cube.ty - (cube.sy * 0.5f);
        const float max_y = cube.ty + (cube.sy * 0.5f);
        const float min_z = cube.tz - (cube.sz * 0.5f);
        const float max_z = cube.tz + (cube.sz * 0.5f);

        emit_quad(glm::vec3(min_x, min_y, min_z), glm::vec3(max_x, min_y, min_z),
                  glm::vec3(max_x, max_y, min_z), glm::vec3(min_x, max_y, min_z),
                  glm::vec3(0.0f, 0.0f, -1.0f));
        emit_quad(glm::vec3(max_x, min_y, max_z), glm::vec3(min_x, min_y, max_z),
                  glm::vec3(min_x, max_y, max_z), glm::vec3(max_x, max_y, max_z),
                  glm::vec3(0.0f, 0.0f, 1.0f));
        emit_quad(glm::vec3(min_x, min_y, max_z), glm::vec3(min_x, min_y, min_z),
                  glm::vec3(min_x, max_y, min_z), glm::vec3(min_x, max_y, max_z),
                  glm::vec3(-1.0f, 0.0f, 0.0f));
        emit_quad(glm::vec3(max_x, min_y, min_z), glm::vec3(max_x, min_y, max_z),
                  glm::vec3(max_x, max_y, max_z), glm::vec3(max_x, max_y, min_z),
                  glm::vec3(1.0f, 0.0f, 0.0f));
        emit_quad(glm::vec3(min_x, min_y, max_z), glm::vec3(max_x, min_y, max_z),
                  glm::vec3(max_x, min_y, min_z), glm::vec3(min_x, min_y, min_z),
                  glm::vec3(0.0f, -1.0f, 0.0f));
        emit_quad(glm::vec3(min_x, max_y, min_z), glm::vec3(max_x, max_y, min_z),
                  glm::vec3(max_x, max_y, max_z), glm::vec3(min_x, max_y, max_z),
                  glm::vec3(0.0f, 1.0f, 0.0f));
    }
}

class MudHudWindow final : public frame::gui::GuiWindowInterface
{
public:
    explicit MudHudWindow(std::function<bool()> draw_callback)
        : draw_callback_(std::move(draw_callback))
    {
    }

    bool DrawCallback() override
    {
        return draw_callback_();
    }

    bool End() const override
    {
        return false;
    }

    std::string GetName() const override
    {
        return name_;
    }

    void SetName(const std::string& name) override
    {
        name_ = name;
    }

private:
    std::function<bool()> draw_callback_;
    std::string name_ = "grpcMUD HUD";
};
} // namespace

int ClientApp::Run(int argc, char** argv)
{
    const auto positional_args = absl::ParseCommandLine(argc, argv);
    if (positional_args.size() > 3)
    {
        std::cerr << "Unexpected positional arguments. Use --help for usage." << std::endl;
        return 1;
    }

    server_address_ = Trim(absl::GetFlag(FLAGS_server_address));
    if (server_address_.empty())
    {
        std::cerr << "Server address cannot be empty." << std::endl;
        return 1;
    }
    if (positional_args.size() > 1)
    {
        server_address_ = Trim(positional_args[1]);
    }

    player_name_ = Trim(absl::GetFlag(FLAGS_player_name));
    if (positional_args.size() > 2)
    {
        player_name_ = Trim(positional_args[2]);
    }
    if (player_name_.empty())
    {
        player_name_ = ReadPlayerNameFromPrompt();
    }

    std::string error_message;
    if (!session_.Connect(server_address_, player_name_, &error_message))
    {
        std::cerr << error_message << std::endl;
        return 1;
    }

    session_.StartReader(
        [this](const mud::v1::ServerMessage& message) { QueueServerMessage(message); },
        [this]() { HandleServerClosed(); });

    AddLog("Connected to " + server_address_ + " as '" + player_name_ + "'.");
    AddLog("3D mode. WASD move/turn, 1/2 attack, 3 guard, Enter chat, Q quit.");
    SendLookRequest();

    std::unique_ptr<frame::WindowInterface> window;
    try
    {
        window = frame::CreateNewWindow(frame::DrawingTargetEnum::WINDOW,
                                        frame::RenderingAPIEnum::OPENGL, kDefaultWindowSize);
    }
    catch (const std::exception& ex)
    {
        std::cerr << "Failed to create 3D window: " << ex.what() << std::endl;
        return 1;
    }
    if (!window)
    {
        std::cerr << "Failed to create 3D window." << std::endl;
        return 1;
    }

    RegisterKeyBindings(*window);

    std::filesystem::path font_path;
    try
    {
        font_path = frame::file::FindFile("external/frame/asset/font/poppins/Poppins-Regular.ttf");
    }
    catch (const std::exception&)
    {
        font_path.clear();
    }

    auto gui = frame::gui::CreateDrawGui(*window, font_path, 18.0f);
    if (gui)
    {
        gui->AddWindow(std::make_unique<MudHudWindow>([this]() { return DrawHud(); }));
        window->GetDevice().AddPlugin(std::move(gui));
    }
    else
    {
        AddLog("[warn] GUI overlay unavailable; controls still active.");
    }

    if (!RebuildSceneIfDirty(*window))
    {
        std::cerr << "[client] Initial scene build failed; continuing with empty frame."
                  << std::endl;
    }

    frame::WindowReturnEnum window_status = frame::WindowReturnEnum::CONTINUE;
    if (running_.load(std::memory_order_relaxed))
    {
        window_status =
            window->Run([this, &window]() { return RenderFrame(*window); });
    }

    if (window_status == frame::WindowReturnEnum::QUIT)
    {
        running_.store(false, std::memory_order_relaxed);
    }

    const grpc::Status status = session_.Shutdown();
    if (!status.ok())
    {
        std::cerr << "RPC ended with error: [" << status.error_code() << "] "
                  << status.error_message() << std::endl;
        return 1;
    }

    return 0;
}

std::string ClientApp::Trim(const std::string& text)
{
    const auto first = text.find_first_not_of(" \t\r\n");
    if (first == std::string::npos)
    {
        return {};
    }
    const auto last = text.find_last_not_of(" \t\r\n");
    return text.substr(first, (last - first) + 1);
}

std::string ClientApp::ToLower(std::string text)
{
    std::transform(text.begin(), text.end(), text.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return text;
}

std::string ClientApp::ReadPlayerNameFromPrompt()
{
    std::string name;
    while (name.empty())
    {
        std::cout << "Enter player name: ";
        if (!std::getline(std::cin, name))
        {
            return {};
        }
        name = Trim(name);
        if (name.empty())
        {
            std::cout << "Player name cannot be empty." << '\n';
        }
    }
    return name;
}

std::string ClientApp::JsonEscape(const std::string& text)
{
    std::string escaped;
    escaped.reserve(text.size() + 16);
    for (const char c : text)
    {
        switch (c)
        {
        case '\\':
            escaped += "\\\\";
            break;
        case '"':
            escaped += "\\\"";
            break;
        case '\n':
            escaped += "\\n";
            break;
        case '\r':
            escaped += "\\r";
            break;
        case '\t':
            escaped += "\\t";
            break;
        default:
            escaped.push_back(c);
            break;
        }
    }
    return escaped;
}

std::string ClientApp::NextRequestId()
{
    return "req-" + std::to_string(request_counter_++);
}

bool ClientApp::SendMessage(mud::v1::ClientMessage message)
{
    if (!session_.SendClientMessage(message))
    {
        AddLog("[error] Failed to send command.");
        std::cerr << "[client] Failed to send command to server." << std::endl;
        return false;
    }
    return true;
}

bool ClientApp::SendLookRequest()
{
    mud::v1::ClientMessage message;
    message.mutable_look()->set_request_id(NextRequestId());
    return SendMessage(std::move(message));
}

bool ClientApp::SendStepRequest(mud::v1::StepKind kind)
{
    mud::v1::ClientMessage message;
    auto* step = message.mutable_step();
    step->set_request_id(NextRequestId());
    step->set_kind(kind);
    return TrySendMoveOrTurnCommand(std::move(message));
}

bool ClientApp::SendSayRequest(const std::string& text)
{
    const std::string trimmed = Trim(text);
    if (trimmed.empty())
    {
        return false;
    }

    mud::v1::ClientMessage message;
    auto* say = message.mutable_say();
    say->set_request_id(NextRequestId());
    say->set_text(trimmed);
    return SendMessage(std::move(message));
}

bool ClientApp::SendGuardRequest()
{
    mud::v1::ClientMessage message;
    message.mutable_guard()->set_request_id(NextRequestId());
    return SendMessage(std::move(message));
}

bool ClientApp::SendAttackRequest(mud::v1::WeaponKind weapon)
{
    mud::v1::ClientMessage message;
    auto* attack = message.mutable_attack();
    attack->set_request_id(NextRequestId());
    attack->set_weapon(weapon);
    return SendMessage(std::move(message));
}

void ClientApp::QueueServerMessage(const mud::v1::ServerMessage& message)
{
    std::lock_guard<std::mutex> lock(pending_messages_mutex_);
    pending_messages_.push_back(message);
}

void ClientApp::ProcessQueuedServerMessages()
{
    std::deque<mud::v1::ServerMessage> pending;
    {
        std::lock_guard<std::mutex> lock(pending_messages_mutex_);
        pending.swap(pending_messages_);
    }

    for (const auto& message : pending)
    {
        HandleServerMessageOnMainThread(message);
    }

    if (server_closed_.load(std::memory_order_relaxed) && !server_closed_logged_)
    {
        AddLog("[system] Connection closed.");
        std::cerr << "[client] Server stream closed. Keeping window open." << std::endl;
        server_closed_logged_ = true;
    }
}

void ClientApp::HandleServerMessageOnMainThread(const mud::v1::ServerMessage& message)
{
    auto maybe_respawn_seconds_from_text = [&](const std::string& text) -> int
    {
        const std::string lowered = ToLower(text);
        const auto marker = lowered.find("respawn in ");
        if (marker == std::string::npos)
        {
            return -1;
        }

        int value = 0;
        bool found_digit = false;
        for (std::size_t i = marker; i < lowered.size(); ++i)
        {
            if (!std::isdigit(static_cast<unsigned char>(lowered[i])))
            {
                if (found_digit)
                {
                    break;
                }
                continue;
            }

            found_digit = true;
            value = (value * 10) + (lowered[i] - '0');
        }
        return found_digit ? value : -1;
    };

    const std::uint64_t message_tick_id = message.tick_id();
    std::uint64_t observed_tick = latest_tick_id_.load(std::memory_order_relaxed);
    while (message_tick_id > observed_tick &&
           !latest_tick_id_.compare_exchange_weak(observed_tick, message_tick_id,
                                                  std::memory_order_relaxed,
                                                  std::memory_order_relaxed))
    {
    }

    switch (message.payload_case())
    {
    case mud::v1::ServerMessage::kJoinAck:
        AddLog("[join] player_id=" + message.join_ack().player_id());
        AddLog("[motd] " + message.join_ack().motd());
        break;
    case mud::v1::ServerMessage::kCommandAck:
        if (!message.command_ack().accepted())
        {
            AddLog("[ack] " + message.command_ack().request_id() + " rejected \"" +
                   message.command_ack().message() + "\"");
            const int respawn_seconds =
                maybe_respawn_seconds_from_text(message.command_ack().message());
            if (respawn_seconds >= 0)
            {
                death_screen_active_ = true;
                death_seconds_remaining_ = respawn_seconds;
            }
        }
        break;
    case mud::v1::ServerMessage::kWorldEvent:
    {
        std::string prefix = "[event]";
        switch (message.world_event().kind())
        {
        case mud::v1::WorldEvent::KIND_ROOM:
            prefix = "[room]";
            break;
        case mud::v1::WorldEvent::KIND_CHAT:
            prefix = "[chat]";
            break;
        case mud::v1::WorldEvent::KIND_SYSTEM:
            prefix = "[system]";
            break;
        case mud::v1::WorldEvent::KIND_COMBAT:
            prefix = "[combat]";
            break;
        case mud::v1::WorldEvent::KIND_UNSPECIFIED:
        default:
            break;
        }

        AddLog(prefix + " " + message.world_event().text());
        const std::string lowered = ToLower(message.world_event().text());
        if (lowered.find("you were knocked out") != std::string::npos)
        {
            death_screen_active_ = true;
            death_seconds_remaining_ = 10;
        }
        else if (lowered.find("you respawn") != std::string::npos)
        {
            death_screen_active_ = false;
            death_seconds_remaining_ = 0;
        }
        break;
    }
    case mud::v1::ServerMessage::kError:
        AddLog("[error] " + message.error().code() + ": " + message.error().message());
        break;
    case mud::v1::ServerMessage::kPong:
        AddLog("[pong]");
        break;
    case mud::v1::ServerMessage::kTick:
        TickDeathScreen();
        break;
    case mud::v1::ServerMessage::kView:
        latest_view_ = message.view();
        scene_dirty_ = true;
        break;
    case mud::v1::ServerMessage::PAYLOAD_NOT_SET:
    default:
        AddLog("[server] message with no payload");
        break;
    }
}

void ClientApp::HandleServerClosed()
{
    server_closed_.store(true, std::memory_order_relaxed);
}

void ClientApp::HandleActionKey(char key)
{
    if (IsInputFocused())
    {
        return;
    }

    key = static_cast<char>(std::tolower(static_cast<unsigned char>(key)));
    if (key == 'q')
    {
        running_.store(false, std::memory_order_relaxed);
        return;
    }

    if (death_screen_active_)
    {
        return;
    }

    if (key == '1')
    {
        SendAttackRequest(mud::v1::WEAPON_KIND_MELEE);
        return;
    }
    if (key == '2')
    {
        SendAttackRequest(mud::v1::WEAPON_KIND_RANGED);
        return;
    }
    if (key == '3')
    {
        SendGuardRequest();
        return;
    }
    if (key == 'p')
    {
        if (!session_.SendPing())
        {
            AddLog("[error] Failed to send ping.");
            running_.store(false, std::memory_order_relaxed);
        }
        return;
    }
    if (key == '/')
    {
        chat_input_buffer_[0] = '/';
        chat_input_buffer_[1] = '\0';
        RequestInputFocus();
        return;
    }
    if (key == 'w' || key == 'k')
    {
        SendStepRequest(mud::v1::STEP_KIND_MOVE_FORWARD);
        return;
    }
    if (key == 'a' || key == 'h')
    {
        SendStepRequest(mud::v1::STEP_KIND_TURN_LEFT);
        return;
    }
    if (key == 's' || key == 'j')
    {
        SendStepRequest(mud::v1::STEP_KIND_MOVE_BACKWARD);
        return;
    }
    if (key == 'd' || key == 'l')
    {
        SendStepRequest(mud::v1::STEP_KIND_TURN_RIGHT);
        return;
    }
}

void ClientApp::HandleSubmittedText(const std::string& text)
{
    if (death_screen_active_)
    {
        AddLog("[dead] Controls are disabled until respawn.");
        return;
    }

    const std::string trimmed = Trim(text);
    if (trimmed.empty())
    {
        return;
    }

    if (trimmed[0] != '/')
    {
        SendSayRequest(trimmed);
        return;
    }

    const std::string command = Trim(trimmed.substr(1));
    const auto split = command.find(' ');
    const std::string verb =
        ToLower(split == std::string::npos ? command : command.substr(0, split));
    const std::string argument =
        Trim(split == std::string::npos ? std::string{} : command.substr(split + 1));
    const std::string normalized_argument = ToLower(argument);

    if (verb == "look")
    {
        SendLookRequest();
        return;
    }
    if (verb == "move")
    {
        if (normalized_argument == "forward" || normalized_argument == "f")
        {
            SendStepRequest(mud::v1::STEP_KIND_MOVE_FORWARD);
            return;
        }
        if (normalized_argument == "backward" || normalized_argument == "back" ||
            normalized_argument == "b")
        {
            SendStepRequest(mud::v1::STEP_KIND_MOVE_BACKWARD);
            return;
        }
        AddLog("[usage] /move <forward|backward>");
        return;
    }
    if (verb == "turn")
    {
        if (normalized_argument == "left" || normalized_argument == "l")
        {
            SendStepRequest(mud::v1::STEP_KIND_TURN_LEFT);
            return;
        }
        if (normalized_argument == "right" || normalized_argument == "r")
        {
            SendStepRequest(mud::v1::STEP_KIND_TURN_RIGHT);
            return;
        }
        AddLog("[usage] /turn <left|right>");
        return;
    }
    if (verb == "say")
    {
        if (argument.empty())
        {
            AddLog("[usage] /say <text>");
            return;
        }
        SendSayRequest(argument);
        return;
    }
    if (verb == "guard")
    {
        SendGuardRequest();
        return;
    }
    if (verb == "attack")
    {
        if (normalized_argument.empty() || normalized_argument == "melee" ||
            normalized_argument == "m")
        {
            SendAttackRequest(mud::v1::WEAPON_KIND_MELEE);
            return;
        }
        if (normalized_argument == "ranged" || normalized_argument == "range" ||
            normalized_argument == "r")
        {
            SendAttackRequest(mud::v1::WEAPON_KIND_RANGED);
            return;
        }
        AddLog("[usage] /attack <melee|ranged>");
        return;
    }
    if (verb == "ping")
    {
        if (!session_.SendPing())
        {
            AddLog("[error] Failed to send ping.");
            running_.store(false, std::memory_order_relaxed);
        }
        return;
    }
    if (verb == "help")
    {
        AddLog("[usage] /look /move /turn /say /guard /attack /ping");
        return;
    }

    AddLog("[usage] Unknown command. Try /look, /move, /turn, /say, /guard, /attack, /ping.");
}

void ClientApp::AddLog(std::string line)
{
    logs_.push_back(std::move(line));
    while (logs_.size() > kMaxLogLines)
    {
        logs_.pop_front();
    }
}

void ClientApp::TickDeathScreen()
{
    if (!death_screen_active_)
    {
        return;
    }
    if (death_seconds_remaining_ > 0)
    {
        --death_seconds_remaining_;
    }
}

bool ClientApp::IsInputFocused() const
{
    return input_focused_;
}

void ClientApp::SetInputFocused(bool focused)
{
    input_focused_ = focused;
}

bool ClientApp::ConsumeInputFocusRequest()
{
    const bool was_requested = input_focus_requested_;
    input_focus_requested_ = false;
    return was_requested;
}

void ClientApp::RequestInputFocus()
{
    input_focus_requested_ = true;
}

std::string ClientApp::BuildBootstrapLevelJson() const
{
    mud::v1::LocalViewUpdate bootstrap;
    bootstrap.set_center_x(0);
    bootstrap.set_center_y(0);
    bootstrap.set_facing(mud::v1::DIRECTION_NORTH);
    auto* square = bootstrap.add_squares();
    square->set_square_id("bootstrap");
    square->set_x(0);
    square->set_y(0);
    square->set_kind(mud::v1::SQUARE_KIND_FLOOR);
    square->set_open_north(true);
    square->set_open_east(true);
    square->set_open_south(true);
    square->set_open_west(true);
    return BuildLevelJsonFromView(bootstrap);
}

std::string ClientApp::BuildLevelJsonFromView(const mud::v1::LocalViewUpdate& view) const
{
    std::unordered_map<std::int64_t, const mud::v1::VisibleSquare*> squares_by_coord;
    squares_by_coord.reserve(static_cast<std::size_t>(view.squares_size()));
    for (const auto& square : view.squares())
    {
        squares_by_coord[CoordKey(square.x(), square.y())] = &square;
    }

    const auto has_square = [&](int x, int y) -> bool
    {
        return squares_by_coord.find(CoordKey(x, y)) != squares_by_coord.end();
    };

    std::vector<CubeSpec> floor_cubes;
    std::vector<CubeSpec> wall_cubes;
    std::vector<CubeSpec> player_cubes;
    std::vector<CubeSpec> npc_cubes;

    int min_square_x = view.center_x();
    int max_square_x = view.center_x();
    int min_square_y = view.center_y();
    int max_square_y = view.center_y();
    for (const auto& square : view.squares())
    {
        min_square_x = std::min(min_square_x, square.x());
        max_square_x = std::max(max_square_x, square.x());
        min_square_y = std::min(min_square_y, square.y());
        max_square_y = std::max(max_square_y, square.y());
    }

    const float base_center_x =
        (static_cast<float>(min_square_x + max_square_x) * 0.5f) * kCellSize;
    const float base_center_z =
        (static_cast<float>(min_square_y + max_square_y) * 0.5f) * kCellSize;
    const float base_span_x =
        (static_cast<float>((max_square_x - min_square_x) + 1) + (2.0f * kBaseFloorMarginCells)) *
        kCellSize;
    const float base_span_z =
        (static_cast<float>((max_square_y - min_square_y) + 1) + (2.0f * kBaseFloorMarginCells)) *
        kCellSize;
    AddCubeSpec(floor_cubes, base_center_x, kBaseFloorCenterY, base_center_z, base_span_x,
                kBaseFloorThickness, base_span_z);

    for (const auto& square : view.squares())
    {
        const float x = static_cast<float>(square.x()) * kCellSize;
        const float z = static_cast<float>(square.y()) * kCellSize;

        if (square.kind() == mud::v1::SQUARE_KIND_WALL)
        {
            AddCubeSpec(wall_cubes, x, kWallCenterY, z, kWallCubeSize, kWallHeight, kWallCubeSize);
            continue;
        }

        AddCubeSpec(floor_cubes, x, kFloorCenterY, z, kCellSize, kFloorThickness, kCellSize);

        if (!square.open_north() && !has_square(square.x(), square.y() - 1))
        {
            AddCubeSpec(wall_cubes, x, kWallCenterY, z - kHalfCell, kCellSize, kWallHeight,
                        kWallThickness);
        }
        if (!square.open_west() && !has_square(square.x() - 1, square.y()))
        {
            AddCubeSpec(wall_cubes, x - kHalfCell, kWallCenterY, z, kWallThickness, kWallHeight,
                        kCellSize);
        }
        if (!square.open_south() && !has_square(square.x(), square.y() + 1))
        {
            AddCubeSpec(wall_cubes, x, kWallCenterY, z + kHalfCell, kCellSize, kWallHeight,
                        kWallThickness);
        }
        if (!square.open_east() && !has_square(square.x() + 1, square.y()))
        {
            AddCubeSpec(wall_cubes, x + kHalfCell, kWallCenterY, z, kWallThickness, kWallHeight,
                        kCellSize);
        }
    }

    for (const auto& actor : view.actors())
    {
        if (actor.kind() == mud::v1::VisibleActor::KIND_SELF)
        {
            continue;
        }

        const float x = static_cast<float>(actor.x()) * kCellSize;
        const float z = static_cast<float>(actor.y()) * kCellSize;
        if (actor.kind() == mud::v1::VisibleActor::KIND_NPC)
        {
            AddCubeSpec(npc_cubes, x, kGroundY + (kNpcHeight * 0.5f), z, kNpcWidth, kNpcHeight,
                        kNpcWidth);
        }
        else
        {
            AddCubeSpec(player_cubes, x, kGroundY + (kPlayerHeight * 0.5f), z, kPlayerWidth,
                        kPlayerHeight, kPlayerWidth);
        }
    }

    const std::filesystem::path model_root = std::filesystem::path("asset") / "model";
    std::filesystem::create_directories(model_root);
    WriteRaytraceObj(model_root / "grpcmud_floor.obj", floor_cubes);
    WriteRaytraceObj(model_root / "grpcmud_wall.obj", wall_cubes);
    WriteRaytraceObj(model_root / "grpcmud_player.obj", player_cubes);
    WriteRaytraceObj(model_root / "grpcmud_npc.obj", npc_cubes);

    const float cam_x = static_cast<float>(view.center_x()) * kCellSize;
    const float cam_z = static_cast<float>(view.center_y()) * kCellSize;
    const FacingVec facing = ToFacingVec(view.facing());
    const float target_x = cam_x + (facing.x * kCameraForwardDistance);
    const float target_z = cam_z + (facing.z * kCameraForwardDistance);

    std::ostringstream json;
    json << "{"
         << "\"name\":\"grpcMUDRaytrace\","
         << "\"default_texture_name\":\"billboard\","
         << "\"textures\":[{"
         << "\"name\":\"billboard\","
         << "\"size\":{\"x\":-1,\"y\":-1},"
         << "\"cubemap\":false,"
         << "\"pixel_element_size\":{\"value\":\"BYTE\"},"
         << "\"pixel_structure\":{\"value\":\"RGB\"}"
         << "}],"
         << "\"programs\":["
         << "{"
         << "\"name\":\"RayTraceProgram\","
         << "\"output_texture_names\":[\"billboard\"],"
         << "\"input_scene_type\":{\"value\":\"QUAD\"},"
         << "\"shader_vertex\":\"grpcmud_raytrace.vert\","
         << "\"shader_fragment\":\"grpcmud_raytrace.frag\","
         << "\"shader_compute\":\"\""
         << ",\"uniforms\":["
         << "{\"name\":\"projection_inv\",\"uniform_enum\":\"PROJECTION_INV_MAT4\"},"
         << "{\"name\":\"view_inv\",\"uniform_enum\":\"VIEW_INV_MAT4\"},"
         << "{\"name\":\"camera_position\",\"uniform_enum\":\"CAMERA_POSITION_VEC3\"},"
         << "{\"name\":\"model_inv\",\"uniform_enum\":\"MODEL_INV_MAT4\"}"
         << "]"
         << "},"
         << "{"
         << "\"name\":\"RayTracePreprocessProgram\","
         << "\"input_scene_type\":{\"value\":\"SCENE\"},"
         << "\"shader_vertex\":\"grpcmud_preprocess.vert\","
         << "\"shader_fragment\":\"grpcmud_preprocess.frag\","
         << "\"shader_compute\":\"\""
         << ",\"uniforms\":["
         << "{\"name\":\"projection\",\"uniform_enum\":\"PROJECTION_MAT4\"},"
         << "{\"name\":\"view\",\"uniform_enum\":\"VIEW_MAT4\"},"
         << "{\"name\":\"model\",\"uniform_enum\":\"MODEL_MAT4\"}"
         << "]"
         << "}"
         << "],"
         << "\"materials\":["
         << "{"
         << "\"name\":\"RayTraceMaterial\","
         << "\"program_name\":\"RayTraceProgram\","
         << "\"preprocess_program_name\":\"RayTracePreprocessProgram\","
         << "\"texture_names\":[],"
         << "\"inner_names\":[],"
         << "\"buffer_names\":[\"FloorMesh.0.triangle\",\"WallMesh.0.triangle\",\"PlayerMesh.0.triangle\",\"NpcMesh.0.triangle\"],"
         << "\"inner_buffer_names\":[\"FloorTriangles\",\"WallTriangles\",\"PlayerTriangles\",\"NpcTriangles\"]"
         << "}"
         << "],"
         << "\"scene_tree\":{"
         << "\"default_root_name\":\"root\","
         << "\"default_camera_name\":\"camera\","
         << "\"node_matrices\":[{\"name\":\"root\",\"matrix\":{\"m11\":1,\"m22\":1,\"m33\":1,\"m44\":1}}],"
         << "\"node_cameras\":[{"
         << "\"name\":\"camera\","
         << "\"parent\":\"root\","
         << "\"position\":{\"x\":" << cam_x << ",\"y\":" << kCameraHeight << ",\"z\":" << cam_z
         << "},"
         << "\"target\":{\"x\":" << target_x << ",\"y\":" << kCameraHeight << ",\"z\":" << target_z
         << "},"
         << "\"up\":{\"x\":0,\"y\":1,\"z\":0},"
         << "\"fov_degrees\":68.0,"
         << "\"aspect_ratio\":1.777777,"
         << "\"near_clip\":" << kCameraNearClip << ","
         << "\"far_clip\":200.0"
         << "}],"
         << "\"node_static_meshes\":["
         << "{\"name\":\"RayTracingRendering\",\"parent\":\"root\",\"mesh_enum\":\"QUAD\",\"material_name\":\"RayTraceMaterial\"},"
         << "{\"name\":\"FloorMesh\",\"parent\":\"root\",\"file_name\":\"grpcmud_floor.obj\",\"material_name\":\"RayTraceMaterial\",\"render_time_enum\":\"PRE_RENDER_TIME\"},"
         << "{\"name\":\"WallMesh\",\"parent\":\"root\",\"file_name\":\"grpcmud_wall.obj\",\"material_name\":\"RayTraceMaterial\",\"render_time_enum\":\"PRE_RENDER_TIME\"},"
         << "{\"name\":\"PlayerMesh\",\"parent\":\"root\",\"file_name\":\"grpcmud_player.obj\",\"material_name\":\"RayTraceMaterial\",\"render_time_enum\":\"PRE_RENDER_TIME\"},"
         << "{\"name\":\"NpcMesh\",\"parent\":\"root\",\"file_name\":\"grpcmud_npc.obj\",\"material_name\":\"RayTraceMaterial\",\"render_time_enum\":\"PRE_RENDER_TIME\"}"
         << "],"
         << "\"node_lights\":[]"
         << "}"
         << "}";
    return json.str();
}

bool ClientApp::RebuildSceneIfDirty(frame::WindowInterface& window)
{
    if (!scene_dirty_)
    {
        return true;
    }

    scene_dirty_ = false;
    try
    {
        const std::string level_json =
            latest_view_ ? BuildLevelJsonFromView(*latest_view_) : BuildBootstrapLevelJson();
        auto level = frame::json::ParseLevel(window.GetSize(), level_json);
        window.GetDevice().Startup(std::move(level));
    }
    catch (const std::exception& ex)
    {
        AddLog(std::string("[error] Failed to rebuild 3D scene: ") + ex.what());
        std::cerr << "[client] Failed to rebuild 3D scene: " << ex.what() << std::endl;
        return false;
    }
    return true;
}

bool ClientApp::RenderFrame(frame::WindowInterface& window)
{
    ProcessQueuedServerMessages();
    if (!RebuildSceneIfDirty(window))
    {
        return running_.load(std::memory_order_relaxed);
    }
    return running_.load(std::memory_order_relaxed);
}

bool ClientApp::DrawHud()
{
    ImGui::TextUnformatted("grpcMUD - 3D client");
    if (death_screen_active_)
    {
        ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f),
                           "You are down. Respawn in %d second(s).", death_seconds_remaining_);
    }
    ImGui::TextUnformatted("Controls: W/S move, A/D turn, 1 melee, 2 ranged, 3 guard, Enter chat.");

    if (ImGui::Button("Look"))
    {
        SendLookRequest();
    }
    ImGui::SameLine();
    if (ImGui::Button("Ping"))
    {
        if (!session_.SendPing())
        {
            AddLog("[error] Failed to send ping.");
            running_.store(false, std::memory_order_relaxed);
        }
    }

    ImGui::Separator();
    ImGui::BeginChild("grpcmud_log_view", ImVec2(0.0f, 220.0f), true);
    for (const auto& line : logs_)
    {
        ImGui::TextWrapped("%s", line.c_str());
    }
    if (ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
    {
        ImGui::SetScrollHereY(1.0f);
    }
    ImGui::EndChild();

    if (ConsumeInputFocusRequest())
    {
        ImGui::SetKeyboardFocusHere();
    }

    const bool submitted = ImGui::InputText("Command / Chat", chat_input_buffer_.data(),
                                            chat_input_buffer_.size(),
                                            ImGuiInputTextFlags_EnterReturnsTrue);
    SetInputFocused(ImGui::IsItemActive() || ImGui::IsItemFocused());

    if (submitted)
    {
        const std::string submitted_text = Trim(chat_input_buffer_.data());
        if (!submitted_text.empty())
        {
            HandleSubmittedText(submitted_text);
        }
        chat_input_buffer_[0] = '\0';
        RequestInputFocus();
    }

    return true;
}

void ClientApp::RegisterKeyBindings(frame::WindowInterface& window)
{
    const auto bind = [&](int keycode, char key)
    {
        window.AddKeyCallback(keycode, [this, key]()
                              {
                                  HandleActionKey(key);
                                  return true;
                              });
    };

    bind(SDLK_Q, 'q');
    bind(SDLK_W, 'w');
    bind(SDLK_A, 'a');
    bind(SDLK_S, 's');
    bind(SDLK_D, 'd');
    bind(SDLK_H, 'h');
    bind(SDLK_J, 'j');
    bind(SDLK_K, 'k');
    bind(SDLK_L, 'l');
    bind(SDLK_1, '1');
    bind(SDLK_2, '2');
    bind(SDLK_3, '3');
    bind(SDLK_P, 'p');
    bind(SDLK_SLASH, '/');

    window.AddKeyCallback(SDLK_RETURN, [this]()
                          {
                              RequestInputFocus();
                              return true;
                          });
    window.AddKeyCallback(SDLK_KP_ENTER, [this]()
                          {
                              RequestInputFocus();
                              return true;
                          });
    window.AddKeyCallback(SDLK_ESCAPE, [this]()
                          {
                              chat_input_buffer_[0] = '\0';
                              SetInputFocused(false);
                              return true;
                          });
}

bool ClientApp::TrySendMoveOrTurnCommand(mud::v1::ClientMessage message)
{
    const std::uint64_t current_tick = latest_tick_id_.load(std::memory_order_relaxed);
    if (move_command_sent_this_tick_ && current_tick == last_move_command_tick_id_)
    {
        AddLog("[move] One move/turn per tick. Wait for next tick.");
        return false;
    }

    if (!SendMessage(std::move(message)))
    {
        return false;
    }

    move_command_sent_this_tick_ = true;
    last_move_command_tick_id_ = current_tick;
    return true;
}
} // namespace grpcmud::client
